//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAC.ProjetoTACFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cidade
    {
        public Cidade()
        {
            this.Endereco = new HashSet<Endereco>();
        }
    
        public int idCidade { get; set; }
        public string Nome { get; set; }
    
        public virtual Estado Estado1 { get; set; }
        public virtual ICollection<Endereco> Endereco { get; set; }
    }
}
