//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAC.ProjetoTACFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contato
    {
        public int IdContato { get; set; }
        public string Nome { get; set; }
        public string Telefone { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DtNacimento { get; set; }
        public string CPF { get; set; }
        public string RG { get; set; }
        public string Detalhes { get; set; }
        public string Numero { get; set; }
        public string Compelmento { get; set; }
    
        public virtual Endereco Endereco { get; set; }
    }
}
